export * from "./Genre/Genre";
export * from "./Header/Header";
export * from "./MovieInfo/MovieInfo";
export * from "./MoviesList/MoviesList";
export * from "./MoviesListCard/MoviesListCard";
export * from "./PosterPreview/PosterPreview";
export * from "./Search/Search";
export * from "./SlideMenu/SlideMenu";
export * from "./StarsRating/StarsRating"
export * from "./UserInfo/UserInfo";